version: '3.8'

services:
  timescaledb:
    image: timescale/timescaledb:latest-pg15
    container_name: instamart_db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=instamart_intelligence
    volumes:
      - timescale_data:/var/lib/postgresql/data

volumes:
  timescale_data:
